### ISSUE TITLE
change-stream?_format=event-source net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by yasser-kfupm** [strongloop/angular-live-set#14]
Hi, 

I noticed there is an error logged to the console after some time and the live-set stop working 

GET http://localhost:3000/api/flights/change-stream?_format=event-source net::ERR_INCOMPLETE_CHUNKED_ENCODING

any idea why is that error happened and what does it mean?

Thanks in advance for the amazing people who worked on this impressive project.

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See h    ttps://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by yasser-kfupm** [comment]
Hi superkhau,

I apologised if I post wrong thing.

 I think it is an issue, I tried the same code with different browsers, however, chrome showing that error and stop working after sometime. 

I did try to post questions on the google groups, however, I didn't find a real sold answer.
I really feel so sorry when there is amazing thing like StrongLoop and it doesn't have responsive community.

**Comment by superkhau** [comment]
We also have a lot of people using [Gitter](https://gitter.im/strongloop/loopback). I'm sure you can find someone there who is willing to help you out.

Anyways, if you believe it to be an issue, please provide a sample repo for us to reproduce the issue on our end. See https://github.com/strongloop/loopback/wiki/Reporting-issues.

**Comment by vgmcglaughlin** [comment]
@yasser-kfupm, I solved the same problem locally by deleting the `"compression": {},` line from my `server/middleware.json` file.

**Comment by superkhau** [comment]
@vgmcglaughlin Cool, closing as resolved then.

**Comment by alexxgathp** [comment]
I am getting this error intermittently in Chrome still, but I am uncertain if it is affecting anything, other than slowed performance and lots of the same error message.

I was getting it all the time with compression turned on, but it became intermittent after removing it, though my implementation is somewhat non-standard and has a couple of the other issues that are open. https://github.com/strongloop/angular-live-set/issues/13

A guy here also has the intermittent version of this issue.
https://github.com/strongloop/loopback/issues/1653#issuecomment-156973549
