### ISSUE TITLE
Run karma tests on CI

### ISSUE THREAD

**Issue by ritch** [strongloop/angular-live-set#3]
Add `npm test` script and ensure tests run on CI

**Comment by rmg** [comment]
Make a grunt task that has `karma` somewhere in the name and then add `grunt task-with-karma-in-name` as the test script. That will ensure that CI properly detects that it uses karma and will know not to try to generate a coverage report itself.

**Comment by ritch** [comment]
@rmg does this apply for `gulp` as well?

**Comment by rmg** [comment]
Yes. It's a bit of a hack. The goal is to have the `scripts.test` match `/karma/` but fail `/mocha/`.
