### ISSUE TITLE
CI failing for node 0.12 on Windows

### ISSUE THREAD

**Issue by superkhau** [strongloop/angular-live-set#31]
See https://github.com/strongloop/angular-live-set/pull/30

**Comment by eddiemonge** [comment]
Fixed. CI needed a kick

**Comment by superkhau** [comment]
Closing, TY @eddiemonge for fixing. Verified.

**Comment by superkhau** [comment]
@bajtos Is it time to remove node 12 from CI? node >=4 in package.json? Whats our strategy there?

**Comment by bajtos** [comment]
AFAICT, angular-live-set is a front-end component that is used by browser apps, therefore the Node.js version should not matter much. It looks like the tests are run in PhantomJS via Karma, so the Node.js version does not matter again.

I am fine with running CI only on Node v4+ versions.

@ritch you are the author of this module, could you please chime in?
