### ISSUE TITLE
Limit and Skip, how to use LiveSet with paging?

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [strongloop/angular-live-set#33]
Hi All,

I can't understand how to use LiveSet with `limit` and `skip`?

Actually, exactly like Facebook, notifications dropdown .. which is realtime notifications + paging

Any ideas?

Thanks.

**Comment by AliBahramiEhsan** [comment]
+1

**Comment by ahmed-abdulmoniem** [comment]
+1
