### ISSUE TITLE
_format=event-source ?

### ISSUE THREAD

**Issue by psi-4ward** [strongloop/angular-live-set#4]
Hi there,
i try to understand the backend side. I didnt find any doc or code about `_format=event-source` ?
Where is the implementation in loopback?

Thanks

**Comment by ritch** [comment]
It's in the strong remoting module

**Comment by raymondfeng** [comment]
`_format` is a query parameter recognized by strong-remoting to specify the expected response media type (related to http Accept header). See https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L462-L469.
